-- AUTOGENERATED SUPABASE ARCHITECTURE PREPARATION & SCHEMA SCRIPTS FOR ZARIA
-- Use this script to instantiate the tables in Supabase with stable constraints.

-- 1. COLLECTIONS / CATEGORIES
create table public.categories (
    id uuid default gen_random_uuid() primary key,
    name text not null,
    "order" integer default 1,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Categories
alter table public.categories enable row level security;
create policy "Allow public read-only access on categories" on public.categories for select using (true);
create policy "Allow all actions on categories for admins" on public.categories for all using (
    auth.jwt() ->> 'email' in (select email from public.users where role in ('admin', 'super_admin'))
);

-- 2. PRODUCTS (with detailed variables, promotional badges, and visual parameters)
create table public.products (
    id uuid default gen_random_uuid() primary key,
    name text not null,
    description text,
    price numeric not null,
    old_price numeric,
    image text,
    category_id uuid references public.categories(id) on delete set null,
    type text default 'clothing' check (type in ('clothing', 'shoes', 'perfume', 'accessory')),
    badge text,
    popular boolean default false,
    is_available boolean default true,
    
    -- Variables parsed from input arrays
    sizes text[] default '{}'::text[],
    pointures text[] default '{}'::text[],
    flacons text[] default '{}'::text[],
    colors text[] default '{}'::text[],
    
    -- Option associations (e.g. mapping colors/variants to secondary images in JSON)
    image_variants jsonb default '[]'::jsonb,
    
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Products
alter table public.products enable row level security;
create policy "Allow public read-only access on products" on public.products for select using (true);
create policy "Allow all actions on products for admins" on public.products for all using (
    auth.jwt() ->> 'email' in (select email from public.users where role in ('admin', 'super_admin', 'editor', 'manager'))
);

-- 3. USERS / CLIENTS & ROLES
create table public.users (
    id uuid references auth.users(id) on delete cascade primary key,
    email text unique not null,
    role text default 'customer' check (role in ('customer', 'viewer', 'staff', 'manager', 'admin', 'super_admin')),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Users
alter table public.users enable row level security;
create policy "Allow users to read their own data" on public.users for select using (auth.uid() = id);
create policy "Allow admins to read all user files" on public.users for select query using (
    auth.jwt() ->> 'email' in (select email from public.users where role in ('admin', 'super_admin'))
);
create policy "Allow admins to manage roles" on public.users for update using (
    auth.jwt() ->> 'email' in (select email from public.users where role in ('admin', 'super_admin'))
);

-- Trigger to automatically create a profile in public.users on user signup:
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, email, role)
  values (new.id, new.email, 'customer');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 4. PROMOTIONS / PROMOS
create table public.promos (
    id uuid default gen_random_uuid() primary key,
    title text not null,
    description text,
    image text,
    discount text, -- ex: '-20%', 'Livraison offerte'
    code text unique, -- ex: 'ZARIA20'
    is_active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.promos enable row level security;
create policy "Allow public read-only promos" on public.promos for select using (true);
create policy "Allow write promos for admins" on public.promos for all using (
    auth.jwt() ->> 'email' in (select email from public.users where role in ('admin', 'super_admin', 'manager'))
);

-- 5. ORDERS / COMMANDES
create table public.orders (
    id uuid default gen_random_uuid() primary key,
    client_id uuid references public.users(id) on delete set null,
    client_email text,
    items jsonb not null, -- List of bought products with selected variables: { name, price, quantity, size, color, pointure, flacon }
    total numeric not null,
    delivery_fee numeric default 0,
    payment_method text check (payment_method in ('mvola', 'airtel', 'omoney', 'cash_boutique', 'card', 'cash_livraison')),
    payment_phone text,
    order_mode text check (order_mode in ('livraison', 'retrait')),
    status text default 'pending' check (status in ('pending', 'confirmed', 'processing', 'delivering', 'completed', 'canceled')),
    shipping_address text,
    shipping_city text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.orders enable row level security;
create policy "Allow customers to view their own orders" on public.orders for select using (auth.uid() = client_id);
create policy "Allow admins to view & edit all orders" on public.orders for all using (
    auth.jwt() ->> 'email' in (select email from public.users where role in ('admin', 'super_admin', 'manager', 'staff'))
);

-- 6. CALLBACKS (Demandes de rappel téléphonique de la clientèle)
create table public.callbacks (
    id uuid default gen_random_uuid() primary key,
    customer_name text not null,
    customer_phone text not null,
    subject text,
    status text default 'pending' check (status in ('pending', 'done', 'ignored')),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.callbacks enable row level security;
create policy "Allow anonymous creation of callbacks" on public.callbacks for insert with check (true);
create policy "Allow staff / admins to view & update callbacks" on public.callbacks for all using (
    auth.jwt() ->> 'email' in (select email from public.users where role in ('admin', 'super_admin', 'manager', 'staff'))
);
